
- service: service.name
  class: boiler.user.user_service.UserService
  arguments:
    - one
    - two
    - three
  shared: False

- service: service2.name
  class: boiler.user.role_service.RoleService
  args:
    - one
    - two
    - three
  kwargs:
    something: something else

- service: service3.name
  class: boiler.tests.di.test_service.TestService
  calls:
    - method: set_tree
      args:
        - one value
        - two value
      kwargs:
        three: '%CONFIG_PATH%'